### ISSUE TITLE
ADTF 2 Conan Package 

### ISSUE THREAD

**Issue by MatthiasU** [AEV/CoRTEX_ADTF2Generator#1]
Hi, 

When I try to run conan in my ADTF project it is looking for the ADTF 2 dependency. 
Where can I find the ADTF 2 conan package ? 

Thank you !

**Comment by Aalmann** [comment]
Hi @MatthiasU 

at first of all thanks for creating the first issue. 👍 

You are right, the generator is looking for a requirement which is named "ADTF" with major version 2 (e.g. `ADTF/2.14.3@<user>/<channel>`). Sadly we cannot directly provide such a package due to license and distribution permission issues.

Please contact the ADTF distributor [Digitalwerk GmbH](https://www.digitalwerk.net/adtf/) via support@digitalwerk.net to get a license and download link at least for the ADTF 2 installer packages. Probably  they may also provide an ADTF 2 conan package (which I cannot guarantee).

I will update the documentation as soon as possible to have all these information available.

Best Aalmann
